<?php
/**
 * AnalysisTemplate
 *
 * PHP version 5
 *
 * @category Class
 * @package  PIWebAPI\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PI Web API 2017 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * OpenAPI spec version: 1.9.0.235
 * Contact: techsupport@osisoft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace PIWebAPI\Client\Model;

use \ArrayAccess;

/**
 * AnalysisTemplate Class Doc Comment
 *
 * @category    Class */
/**
 * @package     PIWebAPI\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AnalysisTemplate implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'AnalysisTemplate';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'web_id' => 'string',
        'id' => 'string',
        'name' => 'string',
        'description' => 'string',
        'path' => 'string',
        'analysis_rule_plug_in_name' => 'string',
        'category_names' => 'string[]',
        'create_enabled' => 'bool',
        'group_id' => 'int',
        'has_notification_template' => 'bool',
        'has_target' => 'bool',
        'output_time' => 'string',
        'target_name' => 'string',
        'time_rule_plug_in_name' => 'string',
        'links' => '\PIWebAPI\Client\Model\AnalysisTemplateLinks'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'web_id' => 'WebId',
        'id' => 'Id',
        'name' => 'Name',
        'description' => 'Description',
        'path' => 'Path',
        'analysis_rule_plug_in_name' => 'AnalysisRulePlugInName',
        'category_names' => 'CategoryNames',
        'create_enabled' => 'CreateEnabled',
        'group_id' => 'GroupId',
        'has_notification_template' => 'HasNotificationTemplate',
        'has_target' => 'HasTarget',
        'output_time' => 'OutputTime',
        'target_name' => 'TargetName',
        'time_rule_plug_in_name' => 'TimeRulePlugInName',
        'links' => 'Links'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'web_id' => 'setWebId',
        'id' => 'setId',
        'name' => 'setName',
        'description' => 'setDescription',
        'path' => 'setPath',
        'analysis_rule_plug_in_name' => 'setAnalysisRulePlugInName',
        'category_names' => 'setCategoryNames',
        'create_enabled' => 'setCreateEnabled',
        'group_id' => 'setGroupId',
        'has_notification_template' => 'setHasNotificationTemplate',
        'has_target' => 'setHasTarget',
        'output_time' => 'setOutputTime',
        'target_name' => 'setTargetName',
        'time_rule_plug_in_name' => 'setTimeRulePlugInName',
        'links' => 'setLinks'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'web_id' => 'getWebId',
        'id' => 'getId',
        'name' => 'getName',
        'description' => 'getDescription',
        'path' => 'getPath',
        'analysis_rule_plug_in_name' => 'getAnalysisRulePlugInName',
        'category_names' => 'getCategoryNames',
        'create_enabled' => 'getCreateEnabled',
        'group_id' => 'getGroupId',
        'has_notification_template' => 'getHasNotificationTemplate',
        'has_target' => 'getHasTarget',
        'output_time' => 'getOutputTime',
        'target_name' => 'getTargetName',
        'time_rule_plug_in_name' => 'getTimeRulePlugInName',
        'links' => 'getLinks'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['web_id'] = isset($data['web_id']) ? $data['web_id'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['path'] = isset($data['path']) ? $data['path'] : null;
        $this->container['analysis_rule_plug_in_name'] = isset($data['analysis_rule_plug_in_name']) ? $data['analysis_rule_plug_in_name'] : null;
        $this->container['category_names'] = isset($data['category_names']) ? $data['category_names'] : null;
        $this->container['create_enabled'] = isset($data['create_enabled']) ? $data['create_enabled'] : null;
        $this->container['group_id'] = isset($data['group_id']) ? $data['group_id'] : null;
        $this->container['has_notification_template'] = isset($data['has_notification_template']) ? $data['has_notification_template'] : null;
        $this->container['has_target'] = isset($data['has_target']) ? $data['has_target'] : null;
        $this->container['output_time'] = isset($data['output_time']) ? $data['output_time'] : null;
        $this->container['target_name'] = isset($data['target_name']) ? $data['target_name'] : null;
        $this->container['time_rule_plug_in_name'] = isset($data['time_rule_plug_in_name']) ? $data['time_rule_plug_in_name'] : null;
        $this->container['links'] = isset($data['links']) ? $data['links'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets web_id
     * @return string
     */
    public function getWebId()
    {
        return $this->container['web_id'];
    }

    /**
     * Sets web_id
     * @param string $web_id
     * @return $this
     */
    public function setWebId($web_id)
    {
        $this->container['web_id'] = $web_id;

        return $this;
    }

    /**
     * Gets id
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param string $id
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     * @param string $name
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     * @param string $description
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets path
     * @return string
     */
    public function getPath()
    {
        return $this->container['path'];
    }

    /**
     * Sets path
     * @param string $path
     * @return $this
     */
    public function setPath($path)
    {
        $this->container['path'] = $path;

        return $this;
    }

    /**
     * Gets analysis_rule_plug_in_name
     * @return string
     */
    public function getAnalysisRulePlugInName()
    {
        return $this->container['analysis_rule_plug_in_name'];
    }

    /**
     * Sets analysis_rule_plug_in_name
     * @param string $analysis_rule_plug_in_name
     * @return $this
     */
    public function setAnalysisRulePlugInName($analysis_rule_plug_in_name)
    {
        $this->container['analysis_rule_plug_in_name'] = $analysis_rule_plug_in_name;

        return $this;
    }

    /**
     * Gets category_names
     * @return string[]
     */
    public function getCategoryNames()
    {
        return $this->container['category_names'];
    }

    /**
     * Sets category_names
     * @param string[] $category_names
     * @return $this
     */
    public function setCategoryNames($category_names)
    {
        $this->container['category_names'] = $category_names;

        return $this;
    }

    /**
     * Gets create_enabled
     * @return bool
     */
    public function getCreateEnabled()
    {
        return $this->container['create_enabled'];
    }

    /**
     * Sets create_enabled
     * @param bool $create_enabled
     * @return $this
     */
    public function setCreateEnabled($create_enabled)
    {
        $this->container['create_enabled'] = $create_enabled;

        return $this;
    }

    /**
     * Gets group_id
     * @return int
     */
    public function getGroupId()
    {
        return $this->container['group_id'];
    }

    /**
     * Sets group_id
     * @param int $group_id
     * @return $this
     */
    public function setGroupId($group_id)
    {
        $this->container['group_id'] = $group_id;

        return $this;
    }

    /**
     * Gets has_notification_template
     * @return bool
     */
    public function getHasNotificationTemplate()
    {
        return $this->container['has_notification_template'];
    }

    /**
     * Sets has_notification_template
     * @param bool $has_notification_template
     * @return $this
     */
    public function setHasNotificationTemplate($has_notification_template)
    {
        $this->container['has_notification_template'] = $has_notification_template;

        return $this;
    }

    /**
     * Gets has_target
     * @return bool
     */
    public function getHasTarget()
    {
        return $this->container['has_target'];
    }

    /**
     * Sets has_target
     * @param bool $has_target
     * @return $this
     */
    public function setHasTarget($has_target)
    {
        $this->container['has_target'] = $has_target;

        return $this;
    }

    /**
     * Gets output_time
     * @return string
     */
    public function getOutputTime()
    {
        return $this->container['output_time'];
    }

    /**
     * Sets output_time
     * @param string $output_time
     * @return $this
     */
    public function setOutputTime($output_time)
    {
        $this->container['output_time'] = $output_time;

        return $this;
    }

    /**
     * Gets target_name
     * @return string
     */
    public function getTargetName()
    {
        return $this->container['target_name'];
    }

    /**
     * Sets target_name
     * @param string $target_name
     * @return $this
     */
    public function setTargetName($target_name)
    {
        $this->container['target_name'] = $target_name;

        return $this;
    }

    /**
     * Gets time_rule_plug_in_name
     * @return string
     */
    public function getTimeRulePlugInName()
    {
        return $this->container['time_rule_plug_in_name'];
    }

    /**
     * Sets time_rule_plug_in_name
     * @param string $time_rule_plug_in_name
     * @return $this
     */
    public function setTimeRulePlugInName($time_rule_plug_in_name)
    {
        $this->container['time_rule_plug_in_name'] = $time_rule_plug_in_name;

        return $this;
    }

    /**
     * Gets links
     * @return \PIWebAPI\Client\Model\AnalysisTemplateLinks
     */
    public function getLinks()
    {
        return $this->container['links'];
    }

    /**
     * Sets links
     * @param \PIWebAPI\Client\Model\AnalysisTemplateLinks $links
     * @return $this
     */
    public function setLinks($links)
    {
        $this->container['links'] = $links;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\PIWebAPI\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\PIWebAPI\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}

