<?php
/**
 * AnalysisLinks
 *
 * PHP version 5
 *
 * @category Class
 * @package  PIWebAPI\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PI Web API 2017 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * OpenAPI spec version: 1.9.0.235
 * Contact: techsupport@osisoft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace PIWebAPI\Client\Model;

use \ArrayAccess;

/**
 * AnalysisLinks Class Doc Comment
 *
 * @category    Class */
/**
 * @package     PIWebAPI\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AnalysisLinks implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'Analysis_Links';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'self' => 'string',
        'target' => 'string',
        'database' => 'string',
        'categories' => 'string',
        'template' => 'string',
        'analysis_rule' => 'string',
        'analysis_rule_plug_in' => 'string',
        'time_rule' => 'string',
        'time_rule_plug_in' => 'string',
        'security' => 'string',
        'security_entries' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'self' => 'Self',
        'target' => 'Target',
        'database' => 'Database',
        'categories' => 'Categories',
        'template' => 'Template',
        'analysis_rule' => 'AnalysisRule',
        'analysis_rule_plug_in' => 'AnalysisRulePlugIn',
        'time_rule' => 'TimeRule',
        'time_rule_plug_in' => 'TimeRulePlugIn',
        'security' => 'Security',
        'security_entries' => 'SecurityEntries'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'self' => 'setSelf',
        'target' => 'setTarget',
        'database' => 'setDatabase',
        'categories' => 'setCategories',
        'template' => 'setTemplate',
        'analysis_rule' => 'setAnalysisRule',
        'analysis_rule_plug_in' => 'setAnalysisRulePlugIn',
        'time_rule' => 'setTimeRule',
        'time_rule_plug_in' => 'setTimeRulePlugIn',
        'security' => 'setSecurity',
        'security_entries' => 'setSecurityEntries'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'self' => 'getSelf',
        'target' => 'getTarget',
        'database' => 'getDatabase',
        'categories' => 'getCategories',
        'template' => 'getTemplate',
        'analysis_rule' => 'getAnalysisRule',
        'analysis_rule_plug_in' => 'getAnalysisRulePlugIn',
        'time_rule' => 'getTimeRule',
        'time_rule_plug_in' => 'getTimeRulePlugIn',
        'security' => 'getSecurity',
        'security_entries' => 'getSecurityEntries'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['self'] = isset($data['self']) ? $data['self'] : null;
        $this->container['target'] = isset($data['target']) ? $data['target'] : null;
        $this->container['database'] = isset($data['database']) ? $data['database'] : null;
        $this->container['categories'] = isset($data['categories']) ? $data['categories'] : null;
        $this->container['template'] = isset($data['template']) ? $data['template'] : null;
        $this->container['analysis_rule'] = isset($data['analysis_rule']) ? $data['analysis_rule'] : null;
        $this->container['analysis_rule_plug_in'] = isset($data['analysis_rule_plug_in']) ? $data['analysis_rule_plug_in'] : null;
        $this->container['time_rule'] = isset($data['time_rule']) ? $data['time_rule'] : null;
        $this->container['time_rule_plug_in'] = isset($data['time_rule_plug_in']) ? $data['time_rule_plug_in'] : null;
        $this->container['security'] = isset($data['security']) ? $data['security'] : null;
        $this->container['security_entries'] = isset($data['security_entries']) ? $data['security_entries'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets self
     * @return string
     */
    public function getSelf()
    {
        return $this->container['self'];
    }

    /**
     * Sets self
     * @param string $self
     * @return $this
     */
    public function setSelf($self)
    {
        $this->container['self'] = $self;

        return $this;
    }

    /**
     * Gets target
     * @return string
     */
    public function getTarget()
    {
        return $this->container['target'];
    }

    /**
     * Sets target
     * @param string $target
     * @return $this
     */
    public function setTarget($target)
    {
        $this->container['target'] = $target;

        return $this;
    }

    /**
     * Gets database
     * @return string
     */
    public function getDatabase()
    {
        return $this->container['database'];
    }

    /**
     * Sets database
     * @param string $database
     * @return $this
     */
    public function setDatabase($database)
    {
        $this->container['database'] = $database;

        return $this;
    }

    /**
     * Gets categories
     * @return string
     */
    public function getCategories()
    {
        return $this->container['categories'];
    }

    /**
     * Sets categories
     * @param string $categories
     * @return $this
     */
    public function setCategories($categories)
    {
        $this->container['categories'] = $categories;

        return $this;
    }

    /**
     * Gets template
     * @return string
     */
    public function getTemplate()
    {
        return $this->container['template'];
    }

    /**
     * Sets template
     * @param string $template
     * @return $this
     */
    public function setTemplate($template)
    {
        $this->container['template'] = $template;

        return $this;
    }

    /**
     * Gets analysis_rule
     * @return string
     */
    public function getAnalysisRule()
    {
        return $this->container['analysis_rule'];
    }

    /**
     * Sets analysis_rule
     * @param string $analysis_rule
     * @return $this
     */
    public function setAnalysisRule($analysis_rule)
    {
        $this->container['analysis_rule'] = $analysis_rule;

        return $this;
    }

    /**
     * Gets analysis_rule_plug_in
     * @return string
     */
    public function getAnalysisRulePlugIn()
    {
        return $this->container['analysis_rule_plug_in'];
    }

    /**
     * Sets analysis_rule_plug_in
     * @param string $analysis_rule_plug_in
     * @return $this
     */
    public function setAnalysisRulePlugIn($analysis_rule_plug_in)
    {
        $this->container['analysis_rule_plug_in'] = $analysis_rule_plug_in;

        return $this;
    }

    /**
     * Gets time_rule
     * @return string
     */
    public function getTimeRule()
    {
        return $this->container['time_rule'];
    }

    /**
     * Sets time_rule
     * @param string $time_rule
     * @return $this
     */
    public function setTimeRule($time_rule)
    {
        $this->container['time_rule'] = $time_rule;

        return $this;
    }

    /**
     * Gets time_rule_plug_in
     * @return string
     */
    public function getTimeRulePlugIn()
    {
        return $this->container['time_rule_plug_in'];
    }

    /**
     * Sets time_rule_plug_in
     * @param string $time_rule_plug_in
     * @return $this
     */
    public function setTimeRulePlugIn($time_rule_plug_in)
    {
        $this->container['time_rule_plug_in'] = $time_rule_plug_in;

        return $this;
    }

    /**
     * Gets security
     * @return string
     */
    public function getSecurity()
    {
        return $this->container['security'];
    }

    /**
     * Sets security
     * @param string $security
     * @return $this
     */
    public function setSecurity($security)
    {
        $this->container['security'] = $security;

        return $this;
    }

    /**
     * Gets security_entries
     * @return string
     */
    public function getSecurityEntries()
    {
        return $this->container['security_entries'];
    }

    /**
     * Sets security_entries
     * @param string $security_entries
     * @return $this
     */
    public function setSecurityEntries($security_entries)
    {
        $this->container['security_entries'] = $security_entries;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\PIWebAPI\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\PIWebAPI\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}

