<?php
/**
 * PointLinks
 *
 * PHP version 5
 *
 * @category Class
 * @package  PIWebAPI\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PI Web API 2017 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * OpenAPI spec version: 1.9.0.235
 * Contact: techsupport@osisoft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace PIWebAPI\Client\Model;

use \ArrayAccess;

/**
 * PointLinks Class Doc Comment
 *
 * @category    Class */
/**
 * @package     PIWebAPI\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PointLinks implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'Point_Links';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'self' => 'string',
        'data_server' => 'string',
        'attributes' => 'string',
        'interpolated_data' => 'string',
        'recorded_data' => 'string',
        'plot_data' => 'string',
        'summary_data' => 'string',
        'value' => 'string',
        'end_value' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'self' => 'Self',
        'data_server' => 'DataServer',
        'attributes' => 'Attributes',
        'interpolated_data' => 'InterpolatedData',
        'recorded_data' => 'RecordedData',
        'plot_data' => 'PlotData',
        'summary_data' => 'SummaryData',
        'value' => 'Value',
        'end_value' => 'EndValue'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'self' => 'setSelf',
        'data_server' => 'setDataServer',
        'attributes' => 'setAttributes',
        'interpolated_data' => 'setInterpolatedData',
        'recorded_data' => 'setRecordedData',
        'plot_data' => 'setPlotData',
        'summary_data' => 'setSummaryData',
        'value' => 'setValue',
        'end_value' => 'setEndValue'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'self' => 'getSelf',
        'data_server' => 'getDataServer',
        'attributes' => 'getAttributes',
        'interpolated_data' => 'getInterpolatedData',
        'recorded_data' => 'getRecordedData',
        'plot_data' => 'getPlotData',
        'summary_data' => 'getSummaryData',
        'value' => 'getValue',
        'end_value' => 'getEndValue'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['self'] = isset($data['self']) ? $data['self'] : null;
        $this->container['data_server'] = isset($data['data_server']) ? $data['data_server'] : null;
        $this->container['attributes'] = isset($data['attributes']) ? $data['attributes'] : null;
        $this->container['interpolated_data'] = isset($data['interpolated_data']) ? $data['interpolated_data'] : null;
        $this->container['recorded_data'] = isset($data['recorded_data']) ? $data['recorded_data'] : null;
        $this->container['plot_data'] = isset($data['plot_data']) ? $data['plot_data'] : null;
        $this->container['summary_data'] = isset($data['summary_data']) ? $data['summary_data'] : null;
        $this->container['value'] = isset($data['value']) ? $data['value'] : null;
        $this->container['end_value'] = isset($data['end_value']) ? $data['end_value'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets self
     * @return string
     */
    public function getSelf()
    {
        return $this->container['self'];
    }

    /**
     * Sets self
     * @param string $self
     * @return $this
     */
    public function setSelf($self)
    {
        $this->container['self'] = $self;

        return $this;
    }

    /**
     * Gets data_server
     * @return string
     */
    public function getDataServer()
    {
        return $this->container['data_server'];
    }

    /**
     * Sets data_server
     * @param string $data_server
     * @return $this
     */
    public function setDataServer($data_server)
    {
        $this->container['data_server'] = $data_server;

        return $this;
    }

    /**
     * Gets attributes
     * @return string
     */
    public function getAttributes()
    {
        return $this->container['attributes'];
    }

    /**
     * Sets attributes
     * @param string $attributes
     * @return $this
     */
    public function setAttributes($attributes)
    {
        $this->container['attributes'] = $attributes;

        return $this;
    }

    /**
     * Gets interpolated_data
     * @return string
     */
    public function getInterpolatedData()
    {
        return $this->container['interpolated_data'];
    }

    /**
     * Sets interpolated_data
     * @param string $interpolated_data
     * @return $this
     */
    public function setInterpolatedData($interpolated_data)
    {
        $this->container['interpolated_data'] = $interpolated_data;

        return $this;
    }

    /**
     * Gets recorded_data
     * @return string
     */
    public function getRecordedData()
    {
        return $this->container['recorded_data'];
    }

    /**
     * Sets recorded_data
     * @param string $recorded_data
     * @return $this
     */
    public function setRecordedData($recorded_data)
    {
        $this->container['recorded_data'] = $recorded_data;

        return $this;
    }

    /**
     * Gets plot_data
     * @return string
     */
    public function getPlotData()
    {
        return $this->container['plot_data'];
    }

    /**
     * Sets plot_data
     * @param string $plot_data
     * @return $this
     */
    public function setPlotData($plot_data)
    {
        $this->container['plot_data'] = $plot_data;

        return $this;
    }

    /**
     * Gets summary_data
     * @return string
     */
    public function getSummaryData()
    {
        return $this->container['summary_data'];
    }

    /**
     * Sets summary_data
     * @param string $summary_data
     * @return $this
     */
    public function setSummaryData($summary_data)
    {
        $this->container['summary_data'] = $summary_data;

        return $this;
    }

    /**
     * Gets value
     * @return string
     */
    public function getValue()
    {
        return $this->container['value'];
    }

    /**
     * Sets value
     * @param string $value
     * @return $this
     */
    public function setValue($value)
    {
        $this->container['value'] = $value;

        return $this;
    }

    /**
     * Gets end_value
     * @return string
     */
    public function getEndValue()
    {
        return $this->container['end_value'];
    }

    /**
     * Sets end_value
     * @param string $end_value
     * @return $this
     */
    public function setEndValue($end_value)
    {
        $this->container['end_value'] = $end_value;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\PIWebAPI\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\PIWebAPI\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}

