<?php
/**
 * AssetDatabaseLinksTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PI Web API 2017 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * OpenAPI spec version: 1.9.0.235
 * Contact: techsupport@osisoft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AssetDatabaseLinksTest Class Doc Comment
 *
 * @category    Class */
// * @description AssetDatabaseLinks
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AssetDatabaseLinksTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "AssetDatabaseLinks"
     */
    public function testAssetDatabaseLinks()
    {

    }

    /**
     * Test attribute "self"
     */
    public function testPropertySelf()
    {

    }

    /**
     * Test attribute "elements"
     */
    public function testPropertyElements()
    {

    }

    /**
     * Test attribute "element_templates"
     */
    public function testPropertyElementTemplates()
    {

    }

    /**
     * Test attribute "event_frames"
     */
    public function testPropertyEventFrames()
    {

    }

    /**
     * Test attribute "asset_server"
     */
    public function testPropertyAssetServer()
    {

    }

    /**
     * Test attribute "element_categories"
     */
    public function testPropertyElementCategories()
    {

    }

    /**
     * Test attribute "attribute_categories"
     */
    public function testPropertyAttributeCategories()
    {

    }

    /**
     * Test attribute "table_categories"
     */
    public function testPropertyTableCategories()
    {

    }

    /**
     * Test attribute "analysis_categories"
     */
    public function testPropertyAnalysisCategories()
    {

    }

    /**
     * Test attribute "analysis_templates"
     */
    public function testPropertyAnalysisTemplates()
    {

    }

    /**
     * Test attribute "enumeration_sets"
     */
    public function testPropertyEnumerationSets()
    {

    }

    /**
     * Test attribute "tables"
     */
    public function testPropertyTables()
    {

    }

    /**
     * Test attribute "security"
     */
    public function testPropertySecurity()
    {

    }

    /**
     * Test attribute "security_entries"
     */
    public function testPropertySecurityEntries()
    {

    }

}
