<?php
/**
 * AttributeTemplateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PI Web API 2017 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * OpenAPI spec version: 1.9.0.235
 * Contact: techsupport@osisoft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AttributeTemplateTest Class Doc Comment
 *
 * @category    Class */
// * @description AttributeTemplate
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AttributeTemplateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "AttributeTemplate"
     */
    public function testAttributeTemplate()
    {

    }

    /**
     * Test attribute "web_id"
     */
    public function testPropertyWebId()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "path"
     */
    public function testPropertyPath()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "type_qualifier"
     */
    public function testPropertyTypeQualifier()
    {

    }

    /**
     * Test attribute "default_units_name"
     */
    public function testPropertyDefaultUnitsName()
    {

    }

    /**
     * Test attribute "default_value"
     */
    public function testPropertyDefaultValue()
    {

    }

    /**
     * Test attribute "data_reference_plug_in"
     */
    public function testPropertyDataReferencePlugIn()
    {

    }

    /**
     * Test attribute "config_string"
     */
    public function testPropertyConfigString()
    {

    }

    /**
     * Test attribute "is_configuration_item"
     */
    public function testPropertyIsConfigurationItem()
    {

    }

    /**
     * Test attribute "is_excluded"
     */
    public function testPropertyIsExcluded()
    {

    }

    /**
     * Test attribute "is_hidden"
     */
    public function testPropertyIsHidden()
    {

    }

    /**
     * Test attribute "is_manual_data_entry"
     */
    public function testPropertyIsManualDataEntry()
    {

    }

    /**
     * Test attribute "has_children"
     */
    public function testPropertyHasChildren()
    {

    }

    /**
     * Test attribute "category_names"
     */
    public function testPropertyCategoryNames()
    {

    }

    /**
     * Test attribute "trait_name"
     */
    public function testPropertyTraitName()
    {

    }

    /**
     * Test attribute "links"
     */
    public function testPropertyLinks()
    {

    }

}
