<?php
/**
 * SecurityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PI Web API 2017 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * OpenAPI spec version: 1.9.0.235
 * Contact: techsupport@osisoft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SecurityTest Class Doc Comment
 *
 * @category    Class */
// * @description Security
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SecurityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Security"
     */
    public function testSecurity()
    {

    }

    /**
     * Test attribute "can_annotate"
     */
    public function testPropertyCanAnnotate()
    {

    }

    /**
     * Test attribute "can_delete"
     */
    public function testPropertyCanDelete()
    {

    }

    /**
     * Test attribute "can_execute"
     */
    public function testPropertyCanExecute()
    {

    }

    /**
     * Test attribute "can_read"
     */
    public function testPropertyCanRead()
    {

    }

    /**
     * Test attribute "can_read_data"
     */
    public function testPropertyCanReadData()
    {

    }

    /**
     * Test attribute "can_subscribe"
     */
    public function testPropertyCanSubscribe()
    {

    }

    /**
     * Test attribute "can_subscribe_others"
     */
    public function testPropertyCanSubscribeOthers()
    {

    }

    /**
     * Test attribute "can_write"
     */
    public function testPropertyCanWrite()
    {

    }

    /**
     * Test attribute "can_write_data"
     */
    public function testPropertyCanWriteData()
    {

    }

    /**
     * Test attribute "has_admin"
     */
    public function testPropertyHasAdmin()
    {

    }

    /**
     * Test attribute "rights"
     */
    public function testPropertyRights()
    {

    }

}
