<?php
/**
 * SecurityIdentityLinksTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PI Web API 2017 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * OpenAPI spec version: 1.9.0.235
 * Contact: techsupport@osisoft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SecurityIdentityLinksTest Class Doc Comment
 *
 * @category    Class */
// * @description SecurityIdentityLinks
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SecurityIdentityLinksTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "SecurityIdentityLinks"
     */
    public function testSecurityIdentityLinks()
    {

    }

    /**
     * Test attribute "self"
     */
    public function testPropertySelf()
    {

    }

    /**
     * Test attribute "asset_server"
     */
    public function testPropertyAssetServer()
    {

    }

    /**
     * Test attribute "security_mappings"
     */
    public function testPropertySecurityMappings()
    {

    }

    /**
     * Test attribute "security"
     */
    public function testPropertySecurity()
    {

    }

    /**
     * Test attribute "security_entries"
     */
    public function testPropertySecurityEntries()
    {

    }

}
