<?php
/**
 * EnumerationSetApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PI Web API 2017 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * OpenAPI spec version: 1.9.0.235
 * Contact: techsupport@osisoft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * EnumerationSetApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EnumerationSetApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for enumerationSetCreateSecurityEntry
     *
     * Create a security entry owned by the enumeration set..
     *
     */
    public function testEnumerationSetCreateSecurityEntry()
    {

    }

    /**
     * Test case for enumerationSetCreateValue
     *
     * Create an enumeration value for a enumeration set..
     *
     */
    public function testEnumerationSetCreateValue()
    {

    }

    /**
     * Test case for enumerationSetDelete
     *
     * Delete an enumeration set..
     *
     */
    public function testEnumerationSetDelete()
    {

    }

    /**
     * Test case for enumerationSetDeleteSecurityEntry
     *
     * Delete a security entry owned by the enumeration set..
     *
     */
    public function testEnumerationSetDeleteSecurityEntry()
    {

    }

    /**
     * Test case for enumerationSetGet
     *
     * Retrieve an enumeration set..
     *
     */
    public function testEnumerationSetGet()
    {

    }

    /**
     * Test case for enumerationSetGetByPath
     *
     * Retrieve an enumeration set by path..
     *
     */
    public function testEnumerationSetGetByPath()
    {

    }

    /**
     * Test case for enumerationSetGetSecurity
     *
     * Get the security information of the specified security item associated with the enumeration set for a specified user..
     *
     */
    public function testEnumerationSetGetSecurity()
    {

    }

    /**
     * Test case for enumerationSetGetSecurityEntries
     *
     * Retrieve the security entries associated with the enumeration set based on the specified criteria. By default, all security entries for this enumeration set are returned..
     *
     */
    public function testEnumerationSetGetSecurityEntries()
    {

    }

    /**
     * Test case for enumerationSetGetSecurityEntryByName
     *
     * Retrieve the security entry associated with the enumeration set with the specified name..
     *
     */
    public function testEnumerationSetGetSecurityEntryByName()
    {

    }

    /**
     * Test case for enumerationSetGetValues
     *
     * Retrieve an enumeration set's values..
     *
     */
    public function testEnumerationSetGetValues()
    {

    }

    /**
     * Test case for enumerationSetUpdate
     *
     * Update an enumeration set by replacing items in its definition..
     *
     */
    public function testEnumerationSetUpdate()
    {

    }

    /**
     * Test case for enumerationSetUpdateSecurityEntry
     *
     * Update a security entry owned by the enumeration set..
     *
     */
    public function testEnumerationSetUpdateSecurityEntry()
    {

    }

}
